### ISSUE TITLE
Buttons not showing up in the drop-down menu..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#25]
* https://wordpress.org/support/topic/button-dropdown-menu-not-displaying-options/

Here's a video provided by the user showing the issue she's having:  https://vimeo.com//220905317

**Comment by tejasm-itpath** [comment]
@angelleye 

I got the issue,
When its select customize button , it will not showing dropdown values 
See this video : https://www.screencast.com/t/c4ulDHQDecf
Can we remove custom button option while there is list from PayPal Button Manager ?
because we can't identify , How many selectbox/textbox are there for PayPal button Manager
May be it is easy way for us

**Comment by tejasm-itpath** [comment]
@angelleye  
**Just inform the client
When he/she update plugin Remove that module and Insert New module and add settings to it so that we can avoid cache problem if any**
