### ISSUE TITLE
Dont see Paypal Button in Divi Visual Builder

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/divi-paypal#28]
HI, I just tried Divi Visual builder ( front-end ) and when I was adding the elements I tried to add PayPal Button but the module was not loaded there. Can you please check and add if possible.
Thanks!

**Comment by tejasm-itpath** [comment]
@angelleye  Removing Won't fix Label because finally Official divi have documentation on how to create custom modules that work on front end too. check this https://www.elegantthemes.com/documentation/developers/divi-module/how-to-create-a-divi-builder-module/ 

Right now in latest divi version it is working but just display Black block on Front end Visual Builder
like this https://www.screencast.com/t/Ww5yl9xTWjlV
Not working as default divi modules are showing the changes so we should add this. But we need to add react js for that as said in documnetation.

**Comment by angelleye** [comment]
@tejasm-itpath So is this related to the Jira issues we already have then?

**Comment by angelleye** [comment]
https://angelleye.atlassian.net/browse/PFD-13
