### ISSUE TITLE
Plugin Conflict..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/divi-paypal#30]
* https://wordpress.org/support/topic/causing-divi-builder-in-backend-to-time-out/
* https://wordpress.org/plugins/shortpixel-image-optimiser/

> So… I have narrowed it down as you have requested…
> 
> When all plugins but yours are deactivated the issue is gone…
> 
> I made an assumption when I got down to it that that was it, not thinking past it, that it might be combining with another plugin lower down.. Perhaps partly because they are pretty much all tried and true plugins I have been using a long time, well supported and updated…
> 
> It is the ShortPixel Image Optimizer plugin that your plugin is hooking up with to cause this issue… When just the two of them are active the issue occurs… When either by themselves is active it goes away…

**Comment by tejasm-itpath** [comment]
@angelleye 
I have installed both the plugin  and latest Divi theme. 
I can reproduce the Timeout error https://www.screencast.com/t/dJiQL119Y0dV
but it is happening every time  not due to PayPal for divi Plugin. If i disabled or remove our plugin still it shows error. So I think it is memory consuming on divi builder loading on backend. 
I have fixed it by adding following code in .htaccess file.

```
<IfModule mod_substitute.c>
SubstituteMaxLineLength 10M
</IfModule>
```

**Comment by angelleye** [comment]
@tejasm-itpath Are we sure this resolved the issue?  The user the reported this says the htaccess update is not fixing the problem for him.

He's also saying the problem only happens with BOTH our plugin and the ShortPixel enabled together.  Can you provide a video demo that shows we are able to reproduce the problem with ShortPixel alone and our plugin not enabled?

**Comment by tejasm-itpath** [comment]
@angelleye 
Yes I can make it. One question Which Divi theme version they using?

**Comment by tejasm-itpath** [comment]
@angelleye 
I have updated to the latest Divi theme and Switched to our plugin's branch #21 
ShortPixel plugin is disabled and it gives me error of timeout  today https://www.screencast.com/t/seL64AOguZ

**Comment by angelleye** [comment]
@tejasm-itpath Not sure why you switched to the specific branch..??  #21 was already merged and released in the plugin updates, so that code is already included if you're running our latest version.  

But now you're saying you're getting this problem even without ShortPixel involved at all..??  If the Divi theme is causing our plugin to break then we need to update our plugin to resolve the issue.

**Comment by tejasm-itpath** [comment]
@angelleye  I switched to older version of the plugin as the client said in the ticket that "For older version it works smoothly". So I switched to the older version and he is right , It is working in older version, Then I track back branch vise  test that which branch cause the issue, And branches 18,19,20 works but then branch 21 not working and throwing this error and continues to latest dev branch.
This was not happened before so I feel 90% problem is due to latest update of Divi theme. 
I don't have exact reason yet. I will check today by doing some more test with old Divi version.

**Comment by angelleye** [comment]
@tejasm-itpath Okay, so yeah, I guess we need to check our latest update with older versions of Divi to see if we can track down exactly which version of Divi this happens with.  Then we can reach out to them to see if they can help us figure out what's going on here as well.

**Comment by tejasm-itpath** [comment]
@angelleye  
I have added condition based on version of the Theme. It was issue from our js file that clearing local storage on every Divi module load.
Now it is working in Old and New Divi themes.
